
import os
import shutil
import tempfile
import zipfile
import getpass
import re
import json

from core.colorable_ops import (
    generate_colorable_skin,
    generate_colorable_skin_variant,
    sanitize_skin_id,
    sanitize_folder_name,
)


def sanitize_mod_name(name: str) -> str:
    return name.strip().replace(" ", "_")


def get_beamng_mods_path():
    try:
        from core.settings import get_mods_folder_path
        configured = get_mods_folder_path()
        if configured and os.path.exists(configured):
            print(f"[DEBUG] Using configured mods path: {configured}")
            return configured
    except ImportError:
        pass

    username = getpass.getuser()
    default  = os.path.join(
        "C:\\Users", username, "AppData", "Local",
        "BeamNG.drive", "0.33", "mods"
    )
    print(f"[DEBUG] Using default mods path: {default}")
    return default


def _find_normal_template(base_carid: str) -> str:
    return os.path.join(os.getcwd(), "vehicles", base_carid, "SKINNAME")


def _find_variant_template(base_carid: str, variant_suffix: str) -> str:
    vehicles_dir = os.path.join(os.getcwd(), "vehicles", base_carid)
    target_lower = f"skinname{variant_suffix.lower()}"

    if os.path.isdir(vehicles_dir):
        for entry in os.listdir(vehicles_dir):
            if entry.lower() == target_lower and os.path.isdir(
                os.path.join(vehicles_dir, entry)
            ):
                found = os.path.join(vehicles_dir, entry)
                print(f"[DEBUG] Found variant template: {found}")
                return found


    fallback = os.path.join(vehicles_dir, f"SKINNAME{variant_suffix.upper()}")
    print(f"[DEBUG] Variant template fallback: {fallback}")
    return fallback


def zip_folder(source_dir, zip_path):
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zipf:
        for root_dir, _, files in os.walk(source_dir):
            for file in files:
                full_path = os.path.join(root_dir, file)
                rel_path  = os.path.relpath(full_path, source_dir)
                zipf.write(full_path, rel_path)


import datetime as _dt

_BSS_VERSION = "BeamSkin Studio"

def _write_bss_watermark(skin_folder: str, mod_name: str, author: str) -> None:
    timestamp = _dt.datetime.now().strftime("%Y-%m-%d %H:%M")

    comment_block = (
        f"// Generated by {_BSS_VERSION}\n"
        f"// https://beamskin-studio.github.io/BeamSkin-Studio-Beta/\n"
        f"// Mod    : {mod_name}\n"
        f"// Author : {author}\n"
        f"// Date   : {timestamp}\n"
    )


    readme_text = (
        f"Generated by {_BSS_VERSION}\n"
        f"https://beamskin-studio.github.io/BeamSkin-Studio-Beta/\n"
        f"\n"
        f"Mod    : {mod_name}\n"
        f"Author : {author}\n"
        f"Date   : {timestamp}\n"
    )
    try:
        with open(os.path.join(skin_folder, "README.txt"), "w", encoding="utf-8") as fh:
            fh.write(readme_text)
    except Exception as e:
        print(f"[WARNING] Could not write README.txt watermark: {e}")


    for fn in os.listdir(skin_folder):
        if not (fn.endswith(".json") or fn.endswith(".jbeam")):
            continue
        fp = os.path.join(skin_folder, fn)
        try:
            with open(fp, "r", encoding="utf-8") as fh:
                original = fh.read()
            with open(fp, "w", encoding="utf-8") as fh:
                fh.write(comment_block + original)
            print(f"[DEBUG] BSS watermark comment added to {fn}")
        except Exception as e:
            print(f"[WARNING] Could not prepend watermark to {fn}: {e}")


def validate_and_fix_dds_filenames(skin_folder_path, car_id):
    results = {"renamed": [], "already_correct": [], "errors": []}
    if not os.path.exists(skin_folder_path):
        results["errors"].append((skin_folder_path, "Folder does not exist"))
        return results

    correct_pattern = re.compile(rf'^{re.escape(car_id)}_skin_.*\.dds$', re.IGNORECASE)

    for filename in os.listdir(skin_folder_path):
        if not filename.lower().endswith(".dds"):
            continue
        file_path = os.path.join(skin_folder_path, filename)
        if correct_pattern.match(filename):
            results["already_correct"].append(filename)
            continue

        if "_skin_" in filename.lower():
            parts     = filename.split("_skin_")
            skin_name = parts[-1].replace(".dds", "").replace(".DDS", "") if len(parts) >= 2 else None
        elif filename.lower().startswith("skin_"):
            skin_name = filename[5:].replace(".dds", "").replace(".DDS", "")
        elif "skin" in filename.lower():
            idx       = filename.lower().find("skin")
            skin_name = filename[idx + 4:].replace(".dds", "").replace(".DDS", "").lstrip("_")
        else:
            skin_name = filename.replace(".dds", "").replace(".DDS", "")

        if not skin_name:
            results["errors"].append((filename, "Could not extract skin name"))
            continue

        new_filename = f"{car_id}_skin_{skin_name}.dds"
        new_file_path = os.path.join(skin_folder_path, new_filename)
        if os.path.exists(new_file_path) and new_file_path != file_path:
            results["errors"].append((filename, f"Target already exists: {new_filename}"))
            continue
        try:
            os.rename(file_path, new_file_path)
            results["renamed"].append((filename, new_filename))
            print(f"[DEBUG] Renamed: {filename} -> {new_filename}")
        except Exception as e:
            results["errors"].append((filename, f"Rename failed: {e}"))

    return results


def process_dds_files_in_mod(temp_mod_root):
    totals = {"renamed": [], "already_correct": [], "errors": [], "skins_processed": 0}
    vehicles_path = os.path.join(temp_mod_root, "vehicles")
    if not os.path.exists(vehicles_path):
        return totals

    for car_id in os.listdir(vehicles_path):
        car_path = os.path.join(vehicles_path, car_id)
        if not os.path.isdir(car_path):
            continue
        for item in os.listdir(car_path):
            item_path = os.path.join(car_path, item)
            if not os.path.isdir(item_path):
                continue
            res = validate_and_fix_dds_filenames(item_path, car_id)
            totals["renamed"].extend([(car_id, item, o, n) for o, n in res["renamed"]])
            totals["already_correct"].extend([(car_id, item, f) for f in res["already_correct"]])
            totals["errors"].extend([(car_id, item, f, e) for f, e in res["errors"]])
            totals["skins_processed"] += 1

    print(f"[DEBUG] DDS processing: {totals['skins_processed']} skins, "
          f"{len(totals['renamed'])} renamed, {len(totals['errors'])} errors")
    return totals


def update_info_json_fields(json_path, config_type, config_name):
    try:
        with open(json_path, "r", encoding="utf-8") as f:
            content = f.read()

        for pattern, value, label in [
            (r'("Config Type"\s*:\s*")[^"]*(")',   config_type, "Config Type"),
            (r'("Configuration"\s*:\s*")[^"]*(")', config_name, "Configuration"),
        ]:
            if re.search(pattern, content):
                content = re.sub(pattern, rf'\g<1>{value}\g<2>', content)
                print(f"[DEBUG]   ✓ Set {label} to: {value}")
            else:
                print(f"[WARNING]   '{label}' key not found in {os.path.basename(json_path)}")

        with open(json_path, "w", encoding="utf-8") as f:
            f.write(content)
        return True
    except Exception as e:
        print(f"[ERROR] update_info_json_fields: {e}")
        return False


def process_skin_config_data(skin_data, base_carid, skin_name, temp_mod_root, template_path):
    if "config_data" not in skin_data:
        return True

    cd          = skin_data["config_data"]
    config_type = cd.get("config_type", "Factory")
    config_name = cd.get("config_name", skin_name)
    pc_path     = cd.get("pc_file_path")
    jpg_path    = cd.get("jpg_file_path")

    print(f"[DEBUG] ===== Config data for {skin_name} =====")

    has_errors = False
    if pc_path and not os.path.exists(pc_path):
        print(f"[ERROR] .pc not found: {pc_path}"); has_errors = True
    if jpg_path and not os.path.exists(jpg_path):
        print(f"[ERROR] .jpg not found: {jpg_path}"); has_errors = True
    if has_errors:
        return False

    try:
        vehicle_root = os.path.join(temp_mod_root, "vehicles", base_carid)
        os.makedirs(vehicle_root, exist_ok=True)

        if pc_path:
            shutil.copy2(pc_path,  os.path.join(vehicle_root, f"{skin_name}.pc"))
            print(f"[DEBUG]   ✓ Copied .pc")
        if jpg_path:
            shutil.copy2(jpg_path, os.path.join(vehicle_root, f"{skin_name}.jpg"))
            print(f"[DEBUG]   ✓ Copied .jpg")


        vehicle_template_root = os.path.dirname(template_path)
        source_info = None
        for fn in ["info.json", "info_template.json"]:
            p = os.path.join(vehicle_template_root, fn)
            if os.path.exists(p):
                source_info = p; break
        if not source_info:
            for fn in os.listdir(vehicle_template_root):
                if fn.startswith("info") and fn.endswith(".json"):
                    source_info = os.path.join(vehicle_template_root, fn); break

        if not source_info:
            print(f"[ERROR] No info.json template in {vehicle_template_root}")
            return False

        dest_info = os.path.join(vehicle_root, f"info_{skin_name}.json")
        shutil.copy2(source_info, dest_info)
        update_info_json_fields(dest_info, config_type, config_name)
        print(f"[DEBUG] ===== Config data complete =====")
        return True

    except Exception as e:
        import traceback
        print(f"[ERROR] process_skin_config_data: {e}")
        traceback.print_exc()
        return False


def process_material_properties(skin_data, base_carid, skin_id, dest_skin_folder):
    if "material_properties" not in skin_data:
        return True

    material_props = skin_data["material_properties"]
    print(f"[DEBUG] ===== Processing material properties for {skin_id} =====")

    mat_files = []
    for root, _, files in os.walk(dest_skin_folder):
        for fn in files:
            if fn.endswith(".materials.json") or fn == "materials.json":
                mat_files.append(os.path.join(root, fn))

    if not mat_files:
        print(f"[WARNING] No .materials.json found in {dest_skin_folder}")
        return False

    try:
        for mat_file in mat_files:
            with open(mat_file, "r", encoding="utf-8") as f:
                content = f.read()
            content = re.sub(r",(\s*[}\]])", r"\1", content)
            try:
                mat_data = json.loads(content)
            except json.JSONDecodeError as e:
                print(f"[ERROR] JSON decode error in {os.path.basename(mat_file)}: {e}")
                continue

            modified = False
            for template_name, stages in material_props.items():
                prefix  = (template_name.split(".skin.")[0]
                           if ".skin." in template_name else template_name)
                actual  = next(
                    (k for k in mat_data if k.startswith(f"{prefix}.skin.")), None
                )
                if not actual or "Stages" not in mat_data[actual]:
                    continue
                for stage_str, props in stages.items():
                    try:
                        idx = int(stage_str)
                    except (ValueError, TypeError):
                        continue
                    if idx >= len(mat_data[actual]["Stages"]):
                        continue
                    for k, v in props.items():
                        old = mat_data[actual]["Stages"][idx].get(k, "NOT_FOUND")
                        mat_data[actual]["Stages"][idx][k] = v
                        modified = True
                        print(f"[DEBUG]   ✓ {actual}.Stages[{idx}].{k}: {old} → {v}")

            if modified:
                with open(mat_file, "w", encoding="utf-8") as f:
                    json.dump(mat_data, f, indent=2)
                print(f"[DEBUG]   Saved {os.path.basename(mat_file)}")

        print(f"[DEBUG] ===== Material properties complete =====")
        return True
    except Exception as e:
        import traceback
        print(f"[ERROR] process_material_properties: {e}")
        traceback.print_exc()
        return False


def process_jbeam_files(folder_path, dds_identifier, skin_display_name, author,
                        dds_prefix=None, carid=None):
    if carid is None:
        carid = dds_prefix

    for root_dir, _, files in os.walk(folder_path):
        for file in files:
            if not file.endswith(".jbeam"):
                continue
            file_path = os.path.join(root_dir, file)
            with open(file_path, "r", encoding="utf-8") as f:
                content = f.read()

            content = re.sub(r'("authors"\s*:\s*")[^"]*(")', rf'\g<1>{author}\g<2>', content)
            content = re.sub(r'("name"\s*:\s*")[^"]*(")', rf'\g<1>{skin_display_name}\g<2>', content)


            if dds_prefix:
                content = re.sub(
                    rf'"({re.escape(dds_prefix)}_skin_)\w*"',
                    rf'"\g<1>{dds_identifier}"',
                    content,
                    flags=re.IGNORECASE,
                )
            else:
                content = re.sub(r'"([^"]+_skin_)SKINNAME\w*"', rf'"\g<1>{dds_identifier}"', content, flags=re.IGNORECASE)


            content = re.sub(r'_skin_SKINNAME\w*', f'_skin_{dds_identifier}', content, flags=re.IGNORECASE)
            content = re.sub(r'("globalSkin"\s*:\s*")[^"]*(")', rf'\g<1>{dds_identifier}\g<2>', content, flags=re.IGNORECASE)
            content = re.sub(r'("skinName"\s*:\s*")[^"]*(")', rf'\g<1>{dds_identifier}\g<2>', content, flags=re.IGNORECASE)

            def _extra(m):      return f'"{m.group(1)}{dds_identifier}"'
            def _extra_name(m): return f'{m.group(1)}{dds_identifier}"'
            content = re.sub(r'"([^"]*_extra\.skin\.)[^"]+"',           _extra,      content)
            content = re.sub(r'("name"\s*:\s*"[^"]*_extra\.skin\.)[^"]+"', _extra_name, content)
            content = re.sub(r'("mapTo"\s*:\s*"[^"]*_extra\.skin\.)[^"]+"',_extra_name, content)

            if carid:
                content = re.sub(r'(?<![a-zA-Z0-9])carid', carid, content, flags=re.IGNORECASE)

            with open(file_path, "w", encoding="utf-8") as f:
                f.write(content)


def process_json_files(folder_path, vehicle_id, skin_folder_name, dds_filename, dds_identifier):
    for root_dir, _, files in os.walk(folder_path):
        for file in files:
            if not file.endswith(".json") or file.startswith("info"):
                continue
            file_path = os.path.join(root_dir, file)
            try:
                with open(file_path, "r", encoding="utf-8") as f:
                    data = json.load(f)

                for mat_key, mat_data in data.items():
                    if not isinstance(mat_data, dict):
                        continue
                    stages = mat_data.get("Stages", [])
                    if len(stages) > 1 and isinstance(stages[1], dict):
                        stage2 = stages[1]
                        if "baseColorMap" in stage2:
                            old = stage2["baseColorMap"]
                            if "SKINNAME" in old.upper():
                                new = re.sub(r'/SKINNAME/', f"/{skin_folder_name}/", old, flags=re.IGNORECASE)
                                new = re.sub(r'_skin_SKINNAME(\.\w+)', f"_skin_{dds_identifier}\\1", new, flags=re.IGNORECASE)
                                new = re.sub(r'(?<![a-zA-Z0-9])carid', vehicle_id, new, flags=re.IGNORECASE)
                            else:
                                new = f"vehicles/{vehicle_id}/{skin_folder_name}/{dds_filename}"
                            stage2["baseColorMap"] = new
                            print(f"[DEBUG] Stage 2 baseColorMap [{mat_key}]: {old} → {new}")

                content = json.dumps(data, indent=2)
            except json.JSONDecodeError:
                with open(file_path, "r", encoding="utf-8") as f:
                    content = f.read()

            def _ref(m):  return f'"{m.group(1)}{dds_identifier}"'
            def _nm(m):   return f'{m.group(1)}{dds_identifier}"'
            content = re.sub(r'"([^"]+\.skin\.)[^"]+"',                     _ref, content)
            content = re.sub(r'"([^"]+\.skin_[^.]*\.)[^"]+"',               _ref, content)
            content = re.sub(r'("name"\s*:\s*"[^"]+\.skin\.)[^"]+"',        _nm,  content)
            content = re.sub(r'("mapTo"\s*:\s*"[^"]+\.skin\.)[^"]+"',       _nm,  content)
            content = re.sub(r'("name"\s*:\s*"[^"]+\.skin_[^.]*\.)[^"]+"',  _nm,  content)
            content = re.sub(r'("mapTo"\s*:\s*"[^"]+\.skin_[^.]*\.)[^"]+"', _nm,  content)
            content = re.sub(r'"([^"]*_extra\.skin\.)[^"]+"',                _ref, content)
            content = re.sub(r'("name"\s*:\s*"[^"]*_extra\.skin\.)[^"]+"',   _nm,  content)
            content = re.sub(r'("mapTo"\s*:\s*"[^"]*_extra\.skin\.)[^"]+"',  _nm,  content)
            content = re.sub(r'/SKINNAME/', f'/{skin_folder_name}/', content, flags=re.IGNORECASE)
            content = re.sub(r'_skin_SKINNAME(\.\w+)', f'_skin_{dds_identifier}\\1', content, flags=re.IGNORECASE)
            content = re.sub(r'(?<![a-zA-Z0-9])carid', vehicle_id, content, flags=re.IGNORECASE)

            with open(file_path, "w", encoding="utf-8") as f:
                f.write(content)


def process_json_files_variant_dds(
    folder_path, vehicle_id, skin_folder_name,
    car_dds_filename,
    var_dds_filename,
    dds_identifier,
    car_skin_folder_name=None,

    variant_suffix="",
):
    car_folder   = car_skin_folder_name or skin_folder_name
    car_dds_path = f"vehicles/{vehicle_id}/{car_folder}/{car_dds_filename}"
    var_dds_path = f"vehicles/{vehicle_id}/{skin_folder_name}/{var_dds_filename}"
    var_prefix   = f"{variant_suffix}.skin."

    for root_dir, _, files in os.walk(folder_path):
        for file in files:
            if not file.endswith(".json") or file.startswith("info"):
                continue
            file_path = os.path.join(root_dir, file)
            print(f"[DEBUG] process_json_files_variant_dds: {file_path}")

            with open(file_path, "r", encoding="utf-8") as f:
                raw = f.read()
            raw_clean = re.sub(r",(\s*[}\]])", r"\1", raw)

            try:
                data      = json.loads(raw_clean); parsed_ok = True
            except json.JSONDecodeError:
                print(f"[WARNING] JSON parse failed: {file_path}"); parsed_ok = False

            if parsed_ok:
                for mat_key, mat_data in data.items():
                    if not isinstance(mat_data, dict):
                        continue
                    stages = mat_data.get("Stages", [])
                    if len(stages) < 2 or not isinstance(stages[1], dict):
                        continue

                    is_var   = mat_key.lower().startswith(var_prefix.lower())
                    dds_path = var_dds_path if is_var else car_dds_path
                    label    = "variant body" if is_var else "car body"

                    old = stages[1].get("baseColorMap", "")
                    stages[1]["baseColorMap"] = dds_path
                    print(f"[DEBUG]   '{mat_key}' ({label}) Stage[1].baseColorMap: {old} → {dds_path}")

                content = json.dumps(data, indent=2)
            else:
                content = raw


            def _ref(m):  return f'"{m.group(1)}{dds_identifier}"'
            def _nm(m):   return f'{m.group(1)}{dds_identifier}"'
            content = re.sub(r'"([^"]+\.skin\.)[^"]+"',                     _ref, content)
            content = re.sub(r'"([^"]+\.skin_[^.]*\.)[^"]+"',               _ref, content)
            content = re.sub(r'("name"\s*:\s*"[^"]+\.skin\.)[^"]+"',        _nm,  content)
            content = re.sub(r'("mapTo"\s*:\s*"[^"]+\.skin\.)[^"]+"',       _nm,  content)
            content = re.sub(r'("name"\s*:\s*"[^"]+\.skin_[^.]*\.)[^"]+"',  _nm,  content)
            content = re.sub(r'("mapTo"\s*:\s*"[^"]+\.skin_[^.]*\.)[^"]+"', _nm,  content)
            content = re.sub(r'"([^"]*_extra\.skin\.)[^"]+"',                _ref, content)
            content = re.sub(r'("name"\s*:\s*"[^"]*_extra\.skin\.)[^"]+"',   _nm,  content)
            content = re.sub(r'("mapTo"\s*:\s*"[^"]*_extra\.skin\.)[^"]+"',  _nm,  content)
            content = re.sub(r'/SKINNAME/', f'/{skin_folder_name}/', content, flags=re.IGNORECASE)
            content = re.sub(r'_skin_SKINNAME(\.\w+)', f'_skin_{dds_identifier}\\1', content, flags=re.IGNORECASE)
            content = re.sub(r'(?<![a-zA-Z0-9])carid', vehicle_id, content, flags=re.IGNORECASE)

            with open(file_path, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"[DEBUG] Processed json (variant-DDS): {file_path}")


def _generate_variant_dds_skin(
    template_path,
    dest_skin_folder,
    base_carid,
    variant_suffix,
    skin,
    skin_folder,
    author,
):
    dds_path_1 = skin["dds_path"]
    dds_path_2 = skin.get("dds_path_2", "")

    if not dds_path_1:
        raise ValueError(f"Missing dds_path for variant skin '{skin['name']}'")
    if not dds_path_2:
        raise ValueError(f"Missing dds_path_2 (variant body DDS) for skin '{skin['name']}'")

    def _ignore_dds(d, f):
        return [x for x in f if x.lower().endswith(".dds")]

    if os.path.exists(dest_skin_folder):
        shutil.rmtree(dest_skin_folder)
    shutil.copytree(template_path, dest_skin_folder, ignore=_ignore_dds)
    print(f"[DEBUG] Variant template copied: {dest_skin_folder}")


    dds_identifier = sanitize_skin_id(skin["name"])
    car_fn = f"{base_carid}_skin_{dds_identifier}.dds"
    var_fn = f"{variant_suffix}_skin_{dds_identifier}.dds"

    shutil.copy(dds_path_1, os.path.join(dest_skin_folder, car_fn))
    shutil.copy(dds_path_2, os.path.join(dest_skin_folder, var_fn))
    print(f"[DEBUG] Copied car-body DDS  : {car_fn}")
    print(f"[DEBUG] Copied variant-body DDS: {var_fn}")

    process_jbeam_files(dest_skin_folder, dds_identifier, skin["name"], author, dds_prefix=base_carid)


    process_json_files_variant_dds(
        dest_skin_folder, base_carid, skin_folder,
        car_fn, var_fn, dds_identifier,
        variant_suffix=variant_suffix,
    )


_STAGE1_KEY_ORDER = [
    "ambientOcclusionMap",
    "useAnisotropic",
    "diffuseMapUseUV",
    "clearCoatFactor",
    "clearCoatRoughnessFactor",
    "metallicFactor",
    "roughnessFactor",
    "metallicMapUseUV",
    "roughnessMapUseUV",
    "metallicMap",
    "roughnessMap",
    "clearCoatMap",
    "normalMap",
    "opacityMap",
    "baseColorMap",
]


def _inject_rough_met(skin_data, base_carid, skin_folder, dest_skin_folder,
                      variant_suffix=""):
    rough_met_src = skin_data.get("rough_met_path", "")
    if not rough_met_src:
        return True
    if not os.path.exists(rough_met_src):
        print(f"[WARNING] rough_met source not found: {rough_met_src}")
        return False

    is_variant = bool(variant_suffix)


    dest_png_1 = os.path.join(dest_skin_folder, "rough_met.png")
    shutil.copy2(rough_met_src, dest_png_1)
    print(f"[DEBUG] Copied rough_met (body): {rough_met_src} → {dest_png_1}")

    var_filename = None
    if is_variant:
        rough_met_src_2 = skin_data.get("rough_met_path_2", "")
        if not rough_met_src_2:
            print(f"[WARNING] rough_met_path_2 missing for variant skin — body file used for both")
            is_variant = False
        elif not os.path.exists(rough_met_src_2):
            print(f"[WARNING] rough_met_path_2 source not found: {rough_met_src_2}")
            is_variant = False
        else:
            var_filename = f"rough_met_{variant_suffix}.png"
            dest_png_2   = os.path.join(dest_skin_folder, var_filename)
            shutil.copy2(rough_met_src_2, dest_png_2)
            print(f"[DEBUG] Copied rough_met (variant body): {rough_met_src_2} → {dest_png_2}")


    ref_body    = f"/vehicles/{base_carid}/{skin_folder}/rough_met.png"
    ref_variant = (
        f"/vehicles/{base_carid}/{skin_folder}/{var_filename}"
        if var_filename else ref_body
    )
    var_prefix  = f"{variant_suffix}.skin."


    mat_files = []
    for root, _, files in os.walk(dest_skin_folder):
        for fn in files:
            if fn.endswith(".materials.json") or fn == "materials.json":
                mat_files.append(os.path.join(root, fn))

    if not mat_files:
        print(f"[WARNING] _inject_rough_met: no .materials.json in {dest_skin_folder}")
        return False

    for mat_file in mat_files:
        with open(mat_file, "r", encoding="utf-8") as fh:
            raw = fh.read()
        raw_clean = re.sub(r",(\s*[}\]])", r"\1", raw)
        try:
            mat_data = json.loads(raw_clean)
        except json.JSONDecodeError as exc:
            print(f"[WARNING] _inject_rough_met JSON error in {os.path.basename(mat_file)}: {exc}")
            continue

        modified = False
        for mat_key, mat_val in mat_data.items():
            if not isinstance(mat_val, dict):
                continue
            stages = mat_val.get("Stages", [])
            if len(stages) < 2 or not isinstance(stages[1], dict):
                continue


            is_var_body = mat_key.lower().startswith(var_prefix.lower())
            ref = ref_variant if (is_var_body and is_variant) else ref_body
            label = "variant body" if (is_var_body and is_variant) else "body"

            stage1 = stages[1]
            stage1["metallicMap"]              = ref
            stage1["roughnessMap"]             = ref
            stage1["metallicMapUseUV"]         = 1
            stage1["roughnessMapUseUV"]        = 1
            stage1["metallicFactor"]           = 0.95
            stage1["roughnessFactor"]          = 0.7
            stage1["clearCoatRoughnessFactor"] = 0.03

            ordered = {k: stage1[k] for k in _STAGE1_KEY_ORDER if k in stage1}
            ordered.update({k: v for k, v in stage1.items() if k not in ordered})
            stages[1] = ordered
            modified = True
            print(f"[DEBUG]   ✓ rough_met ({label}) injected into '{mat_key}' Stage[1] → {ref}")

        if modified:
            with open(mat_file, "w", encoding="utf-8") as fh:
                json.dump(mat_data, fh, indent=2)
            print(f"[DEBUG]   Saved {os.path.basename(mat_file)}")

    return True


def generate_mod(
    mod_name, vehicle_id, skin_display_name, dds_path,
    output_path=None, progress_callback=None, author=None,
):
    print(f"\n{'='*60}\nSINGLE SKIN MOD GENERATION\n{'='*60}")
    mod_name      = sanitize_mod_name(mod_name)
    template_path = _find_normal_template(vehicle_id)
    if not os.path.exists(template_path):
        raise FileNotFoundError(f"No template found for vehicle '{vehicle_id}'")

    temp_dir = tempfile.mkdtemp()
    try:
        dest = os.path.join(temp_dir, "vehicles", vehicle_id, mod_name)
        if os.path.exists(dest):
            shutil.rmtree(dest)
        shutil.copytree(template_path, dest,
                        ignore=lambda d, f: [x for x in f if x.lower().endswith(".dds")])
        if progress_callback: progress_callback(0.2)

        dds_filename   = os.path.basename(dds_path)
        shutil.copy(dds_path, os.path.join(dest, dds_filename))
        dds_identifier = os.path.splitext(dds_filename)[0].split("_")[-1]
        if progress_callback: progress_callback(0.4)

        process_jbeam_files(dest, dds_identifier, skin_display_name, author or "Unknown", dds_prefix=vehicle_id)
        if progress_callback: progress_callback(0.6)
        process_json_files(dest, vehicle_id, mod_name, dds_filename, dds_identifier)
        _write_bss_watermark(dest, mod_name, author or "Unknown")
        if progress_callback: progress_callback(0.8)

        mods_path = output_path or get_beamng_mods_path()
        os.makedirs(mods_path, exist_ok=True)
        zip_path = os.path.join(mods_path, f"{mod_name}.zip")
        zip_folder(temp_dir, zip_path)
        if progress_callback: progress_callback(1.0)
        return zip_path
    finally:
        if os.path.exists(temp_dir):
            shutil.rmtree(temp_dir)


def generate_multi_skin_mod(project_data, output_path=None, progress_callback=None, unpacked=False):
    print(f"\n{'='*60}\nMULTI-SKIN MOD GENERATION\n{'='*60}")

    mod_name    = sanitize_mod_name(project_data["mod_name"])
    author      = project_data.get("author", "Unknown")
    cars        = project_data["cars"]
    total_cars  = len(cars)
    total_skins = sum(len(ci["skins"]) for ci in cars.values())

    print(f"Mod:    {mod_name}")
    print(f"Author: {author}")
    print(f"Cars:   {total_cars}   Skins: {total_skins}")


    for car_instance_id, car_info in cars.items():
        base_carid = car_info.get("base_carid", car_instance_id)
        _vsuffix   = car_info.get("variant_suffix", "")
        seen_folders: dict = {}
        for skin in car_info.get("skins", []):
            folder = sanitize_folder_name(skin["name"]) + _vsuffix
            if folder in seen_folders:
                raise ValueError(
                    f"Vehicle '{base_carid}' has two skins that produce the same "
                    f"folder name '{folder}':\n"
                    f"  • {seen_folders[folder]!r}\n"
                    f"  • {skin['name']!r}\n\n"
                    f"Please give each skin a unique name."
                )
            seen_folders[folder] = skin["name"]

    temp_dir = tempfile.mkdtemp()
    print(f"Temp:   {temp_dir}")

    try:
        processed_skins = 0

        for car_instance_id, car_info in cars.items():
            base_carid     = car_info.get("base_carid", car_instance_id)
            variant_suffix = car_info.get("variant_suffix", "")
            skins          = car_info["skins"]


            is_variant     = variant_suffix != ""


            try:
                from core.config import is_single_layer_variant, is_rebadge_suffix
            except ImportError:
                def is_single_layer_variant(_c, _s): return False
                def is_rebadge_suffix(_c, _s): return False
            needs_double_layer = is_variant and not is_single_layer_variant(base_carid, variant_suffix)


            if is_variant and is_rebadge_suffix(base_carid, variant_suffix):
                dds_prefix = variant_suffix.lower()
            else:
                dds_prefix = base_carid

            print(f"\n--- {base_carid}"
                  f"{f' [{variant_suffix}]' if is_variant else ''}"
                  f" ({len(skins)} skins) ---")


            if is_variant:
                template_path = _find_variant_template(base_carid, variant_suffix)
            else:
                template_path = _find_normal_template(base_carid)

            if not os.path.exists(template_path):
                raise FileNotFoundError(
                    f"No template found for vehicle '{base_carid}'"
                    f"{f' variant={variant_suffix}' if is_variant else ''}.\n"
                    f"Expected: {template_path}\n\n"
                    f"Make sure the vehicle (and its variant template) exists "
                    f"in the Developer tab."
                )


            for skin_idx, skin in enumerate(skins):
                skin_name    = skin["name"]
                skin_id      = sanitize_skin_id(skin_name)


                skin_folder  = sanitize_folder_name(skin_name) + (variant_suffix if is_variant else "")
                is_colorable = skin.get("is_colorable", False)

                print(f"  [{skin_idx+1}/{len(skins)}] '{skin_name}' → {skin_folder}"
                      f" ({'colorable' if is_colorable else 'DDS'}"
                      f"{' + variant' if is_variant else ''}"
                      f"{' (single-layer)' if is_variant and not needs_double_layer else ''})")

                dest_skin_folder = os.path.join(
                    temp_dir, "vehicles", base_carid, skin_folder
                )


                if is_colorable:
                    if needs_double_layer:

                        generate_colorable_skin_variant(
                            template_path      = template_path,
                            dest_skin_folder   = dest_skin_folder,
                            vehicle_id         = base_carid,
                            variant_suffix     = variant_suffix,
                            skin_name          = skin_name,
                            skin_folder        = skin_folder,
                            data_map_source    = skin["data_map_path"],
                            color_map_source   = skin["color_map_path"],
                            data_map_source_2  = skin["data_map_path_2"],
                            color_map_source_2 = skin["color_map_path_2"],
                            author_name        = author,
                            material_properties= skin.get("material_properties"),
                        )
                    else:

                        generate_colorable_skin(
                            template_path      = template_path,
                            dest_skin_folder   = dest_skin_folder,
                            vehicle_id         = base_carid,
                            skin_name          = skin_name,
                            skin_folder        = skin_folder,
                            data_map_source    = skin["data_map_path"],
                            color_map_source   = skin["color_map_path"],
                            author_name        = author,
                            material_properties= skin.get("material_properties"),
                        )


                else:
                    if needs_double_layer:

                        _generate_variant_dds_skin(
                            template_path    = template_path,
                            dest_skin_folder = dest_skin_folder,
                            base_carid       = base_carid,
                            variant_suffix   = variant_suffix,
                            skin             = skin,
                            skin_folder      = skin_folder,
                            author           = author,
                        )
                    else:

                        dds_path = skin["dds_path"]

                        if os.path.exists(dest_skin_folder):
                            shutil.rmtree(dest_skin_folder)
                        shutil.copytree(
                            template_path, dest_skin_folder,
                            ignore=lambda d, f: [x for x in f if x.lower().endswith(".dds")]
                        )


                        dds_identifier = skin_id
                        dds_filename   = f"{dds_prefix}_skin_{skin_id}.dds"
                        shutil.copy(dds_path, os.path.join(dest_skin_folder, dds_filename))

                        process_jbeam_files(
                            dest_skin_folder, dds_identifier, skin_name, author,
                            dds_prefix=dds_prefix, carid=base_carid,
                        )
                        process_json_files(
                            dest_skin_folder, base_carid, skin_folder,
                            dds_filename, dds_identifier,
                        )


                if "config_data" in skin:
                    print(f"  → Config data...")
                    ok = process_skin_config_data(
                        skin, base_carid, skin_folder, temp_dir, template_path
                    )
                    if not ok:
                        print(f"  [WARNING] Config data failed for {skin_folder}")


                if "material_properties" in skin and not is_colorable:
                    print(f"  → Material properties...")
                    ok = process_material_properties(
                        skin, base_carid, skin_folder, dest_skin_folder
                    )
                    if not ok:
                        print(f"  [WARNING] Material properties failed for {skin_folder}")


                if "rough_met_path" in skin:
                    print(f"  → Reflectivity map...")
                    ok = _inject_rough_met(
                        skin, base_carid, skin_folder, dest_skin_folder,
                        variant_suffix=variant_suffix,
                    )
                    if not ok:
                        print(f"  [WARNING] Reflectivity map injection failed for {skin_folder}")


                _write_bss_watermark(dest_skin_folder, mod_name, author)

                processed_skins += 1
                if progress_callback:
                    progress_callback(0.1 + (processed_skins / total_skins) * 0.75)


        print(f"\n{'='*60}\nVALIDATING DDS FILENAMES\n{'='*60}")
        dds_results = process_dds_files_in_mod(temp_dir)

        if dds_results["renamed"]:
            print(f"✓ Fixed {len(dds_results['renamed'])} DDS filename(s)")
            for car_id, skin_folder, old_dds, new_dds in dds_results["renamed"]:
                skin_folder_path = os.path.join(temp_dir, "vehicles", car_id, skin_folder)
                for mat_fn in ["skin.materials.json", "materials.json"]:
                    mat_path = os.path.join(skin_folder_path, mat_fn)
                    if os.path.exists(mat_path):
                        try:
                            with open(mat_path, "r", encoding="utf-8") as f:
                                content = f.read()
                            old_path = f"vehicles/{car_id}/{skin_folder}/{old_dds}"
                            new_path = f"vehicles/{car_id}/{skin_folder}/{new_dds}"
                            if old_path in content:
                                content = content.replace(old_path, new_path)
                                with open(mat_path, "w", encoding="utf-8") as f:
                                    f.write(content)
                                print(f"  Updated {car_id}/{skin_folder}/{mat_fn}")
                        except Exception as e:
                            print(f"  [WARNING] materials.json update failed: {e}")


        print(f"\n{'Copying unpacked mod folder' if unpacked else 'Creating ZIP'}…")
        if progress_callback:
            progress_callback(0.9)

        mods_path = output_path or get_beamng_mods_path()
        os.makedirs(mods_path, exist_ok=True)

        if unpacked:
            dest_folder = os.path.join(mods_path, mod_name)
            if os.path.exists(dest_folder):
                raise FileExistsError(
                    f"A mod folder named '{mod_name}' already exists.\n"
                    f"Please choose a different name or delete the existing folder."
                )
            shutil.copytree(temp_dir, dest_folder)
            if progress_callback:
                progress_callback(1.0)
            print(f"\n✓ Multi-skin mod created (unpacked)!")
            print(f"  Cars: {total_cars}  Skins: {total_skins}")
            print(f"  Location: {dest_folder}")
            print(f"{'='*60}\n")
            return dest_folder
        else:
            zip_path = os.path.join(mods_path, f"{mod_name}.zip")
            if os.path.exists(zip_path):
                raise FileExistsError(
                    f"A mod named '{mod_name}.zip' already exists.\n"
                    f"Please choose a different name or delete the existing file."
                )
            print(f"[DEBUG] Files to zip from {temp_dir}:")
            for root, _, files in os.walk(temp_dir):
                for file in files:
                    print(f"[DEBUG]   {os.path.relpath(os.path.join(root, file), temp_dir)}")
            zip_folder(temp_dir, zip_path)
            if progress_callback:
                progress_callback(1.0)
            print(f"\n✓ Multi-skin mod created!")
            print(f"  Cars: {total_cars}  Skins: {total_skins}")
            print(f"  Location: {zip_path}")
            print(f"{'='*60}\n")
            return zip_path

    finally:
        if os.path.exists(temp_dir):
            shutil.rmtree(temp_dir)
